# Generated by Django 3.0.7 on 2020-06-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('mape', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('price_predict', models.FloatField(default=0)),
            ],
        ),
    ]
