# Generated by Django 3.0.7 on 2020-06-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.CharField(default='low', max_length=400),
        ),
        migrations.AddField(
            model_name='user',
            name='risk',
            field=models.CharField(default='low', max_length=400),
        ),
        migrations.AddField(
            model_name='user',
            name='time_invest',
            field=models.CharField(default='low', max_length=400),
        ),
        migrations.AlterField(
            model_name='user',
            name='answers',
            field=models.CharField(default='low', max_length=400),
        ),
    ]
