# Generated by Django 3.0.7 on 2020-06-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200607_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='rec_day',
        ),
        migrations.AddField(
            model_name='stock',
            name='rec_day_new',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
