# Generated by Django 3.0.7 on 2020-06-07 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200607_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='reg_day_past',
        ),
    ]
